#!/usr/bin/python3
import socket
import sys
from _thread import *
import select 
import re 

if len(sys.argv)!=2:
    print("Input format be = ./chatserver ip:port ")
    sys.exit()

server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)

